import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {notFound} from "next/navigation";
import {Check,ExternalLink,MessageCircle} from "lucide-react";
import {getPublicTemplateBySlug} from "@/lib/templates";
import {formatPrice} from "@/lib/utils";
import {generateWhatsAppUrl,whatsappMessages} from "@/lib/whatsapp";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const item=await getPublicTemplateBySlug(slug);if(!item)return{};return{title:item.name,description:item.shortDescription,openGraph:{title:`${item.name} | INVITA DIGITAL`,description:item.shortDescription,images:[item.coverImage]},twitter:{card:"summary_large_image",images:[item.coverImage]}}}
export default async function TemplateDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=await getPublicTemplateBySlug(slug);if(!item)notFound();const message=item.whatsappMessage||whatsappMessages.template(item.name);return <section className="section-pad"><div className="container-site"><Link href="/plantillas" className="text-sm font-semibold text-gold">← Volver al catálogo</Link><div className="mt-6 grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="grid gap-3 sm:grid-cols-2"><div className="relative aspect-[4/5] overflow-hidden rounded-2xl sm:col-span-2"><Image src={item.coverImage} alt={item.name} fill sizes="(max-width:1024px) 100vw, 55vw" priority className="object-cover"/></div>{item.images.map((image,index)=><div key={`${image}-${index}`} className="relative aspect-[4/3] overflow-hidden rounded-2xl"><Image src={image} alt={`${item.name}, vista ${index+2}`} fill sizes="(max-width:640px) 100vw, 28vw" className="object-cover"/></div>)}</div><div className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow">{item.category} · {item.style}</p><h1 className="display mt-3 text-5xl text-navy">{item.name}</h1><div className="mt-5 flex items-center gap-3"><p className="text-2xl font-bold text-navy">Desde {formatPrice(item.price)}</p>{item.previousPrice&&<p className="text-lg text-slate-400 line-through">{formatPrice(item.previousPrice)}</p>}</div><p className="prose-copy mt-5">{item.description}</p><h2 className="mt-8 font-bold text-navy">Esta invitación puede incluir:</h2><ul className="mt-4 grid gap-3 sm:grid-cols-2">{item.features.map(feature=><li key={feature} className="flex items-center gap-2 text-sm text-slate-600"><Check size={17} className="text-gold"/>{feature}</li>)}</ul><div className="mt-8 grid gap-3 sm:grid-cols-2">{item.demoUrl!=="#"&&<a href={item.demoUrl} target="_blank" rel="noreferrer" className="btn-secondary">Ver demostración <ExternalLink size={16}/></a>}<a href={generateWhatsAppUrl(message)} target="_blank" rel="noreferrer" className="btn-primary"><MessageCircle size={17}/>Quiero esta plantilla</a></div><p className="mt-4 text-xs text-slate-400">La demostración es ilustrativa. Personalizaremos nombres, fotos, colores e información.</p></div></div></div></section>}
